import Head from 'next/head'
import OffcanvasExample from '../components/navbar'
import Container from 'react-bootstrap/Container'
import Col from 'react-bootstrap/Col'
import Row from 'react-bootstrap/Row'
import Image from 'react-bootstrap/Image'
import { Button, Modal } from 'react-bootstrap'
import Cards from '../components/cards'
import FirstSection from '../components/firstSection'
import { useState } from 'react'
import { useEffect } from 'react'


export default function Home() {

  const [modalShow, setModalShow] = useState(false);

  function MyVerticallyCenteredModal(props) {
    return (
      <Modal
        {...props}
        backdrop="static"
        keyboard={false}
        aria-labelledby="contained-modal-title-vcenter"
        centered
      >
        <Modal.Header>
          <Modal.Title id="contained-modal-title-vcenter">
            Age Confirmation
          </Modal.Title>
        </Modal.Header>
        <Modal.Body className='text-center'>
        {/* <iframe src="https://embed.lottiefiles.com/animation/19539" className='m-auto my-4' /> */}
          <h4>Are you 21 or older?</h4>
          <p>Our content is age restricted for guests above 21 years old</p>
        </Modal.Body>
        <Modal.Footer>
          <Button onClick={props.onHide} >Yes I,am</Button>
          <Button href='https://www.google.com/search?q=9ice' variant="secondary">No</Button>
        </Modal.Footer>
      </Modal>
    );
  }

  useEffect(()=>{
    setModalShow(true);
  },[])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-[url('/background/allFinal.png')] bg-fixed bg-cover bg-center">
        
          <OffcanvasExample />
          
      <Container fluid className='mt-14'>
      <Row>
        <Col xs={6} lg={4} className='bg-red-300 text-center hover:scale-105'>
          <p className='mt-8 text-red-900 text-3xl font-extrabold'>Rolling Paper</p>
          <Image 
          src="/background/boxFinal.png"
          className='mt-8 scale-[140%]'
          />
        </Col>
        <Col xs={6} lg={4} className='bg-blue-300 text-center hover:scale-105'>
        <p className='mt-8 text-blue-900 text-3xl font-extrabold'>Cigarillos</p>
          <Image 
          src="/background/cigFinal.png"
          className='m-auto'
          />
        </Col>
        <Col xs={12} lg={4} className='bg-green-300 text-center hover:scale-105'>
        <p className='mt-8 text-green-900 text-3xl font-extrabold'>Cones</p>
          <Image 
          src="/background/coneFinal.png"
          className='m-auto'
          />
        </Col>
      </Row>
    </Container>

    <div>
    {/* <Button variant="primary" onClick={() => setModalShow(true)}>
        Launch vertically centered modal
      </Button> */}
      <MyVerticallyCenteredModal
        show={modalShow}
        onHide={() => setModalShow(false)}
      />
        </div>

    <div className='bg-white pb-12'>
    <FirstSection />
    </div>

    <Container fluid>
      <Row>
      <Col className='text-center mt-2 mb-6 text-gray-700 p-12'>
         <div className=' w-[80%] m-auto p-4 mb-8 rounded-lg bg-white opacity-[65%] text-black'>
         <div className='text-3xl font-semibold my-4'>Know about us</div>
         <div className='text-lg w-[70%] m-auto mb-4'>We are the first hand rolWe are the first hand rolled flavored We are the first hand rolled 
          flavored led flavored We are the first hand rolled flavored We are the first hand rolled flavored We are the first hand rolWe are the first hand rolled flavored We are the first hand rolled 
          flavored led flavored We are the first hand rolled flavored We are the first hand rolled flavored</div>
         </div>
        </Col>
      </Row>
    </Container>

    <Container fluid className='mb-10 bg-white'>
      <Row>
      <Col className='text-center mt-4'>
         <div className='text-3xl font-semibold my-4'>Product Categories</div> 
        </Col>
      </Row>
      <Row>
        <Col xs={12} sm={6} md={4}>
          <div className='bg-red-100 m-4 rounded-full hover:scale-110 hover:bg-red-300'>
            <Image 
            src="/background/boxFinal.png"
            className='h-[300px] m-auto p-2'
            />
          </div>
          <p className='text-red-900 text-xl font-bold text-center'>Rolling Paper</p>
        </Col>
        <Col xs={12} sm={6} md={4}>
          <div className='bg-blue-100 m-4 rounded-full hover:scale-110 hover:bg-blue-300'>
            <Image 
            src="/background/cigFinal.png"
            className='h-[300px] m-auto p-2'
            />
          </div>
          <p className='text-blue-900 text-xl font-bold text-center'>Cigarillos</p>
        </Col>
        <Col xs={12} sm={6} md={4}>
          <div className='bg-green-100 m-4 rounded-full hover:scale-110 hover:bg-green-300'>
            <Image 
            src="/background/coneFinal.png"
            className='h-[300px] m-auto p-2'
            />
          </div>
          <p className='text-green-900 text-xl font-bold text-center'>Cones</p>
        </Col>
      </Row>
    </Container>

    <Container fluid>
      <Row>
      <Col className='text-center mt-2 mb-6 text-gray-700 p-8'>
         <div className=' w-[80%] m-auto p-4 mb-8 rounded-lg bg-white opacity-[65%] text-black'>
         <div className='text-3xl font-semibold my-4'>Connect With Us</div>
         <div className='text-lg w-[70%] m-auto mb-4'>We are the first hand rolWe are the first hand rolled flavored We are the first hand rolled 
          flavored led flavored We are the first hand rolled flavored We are the first hand rolled flavored We are the first hand rolWe are the first hand rolled flavored We are the first hand rolled 
          flavored led flavored We are the first hand rolled flavored We are the first hand rolled flavored</div>
         </div>
        </Col>
      </Row>
    </Container>

    <Container fluid className=' bg-white' >
      <Row>
        <Col sm={8}>
          <Container className='my-4'>
            <Row>
              <Col>Any details</Col>
              <Col>Any details</Col>
              <Col>Any details</Col>
            </Row>
          </Container>
        </Col>
        <Col sm={4}>
        <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSe5jWUn6n6RKRb74-SwMq25opGAC6GFRACC1hl5RyCf2Xf7Og/viewform?embedded=true" width="640" height="200" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
        </Col>
      </Row>
      <Row className='bg-gray-400 text-center p-1'>
        <p className='text-center text-lg font-semibold'>All rights are reserved to 9ICE.in</p>
      </Row>
    </Container>
    </div>
      </main>
    </>
  )
}
